export const SITE_SETTING_KEYS = {
  SITE_NAME: 'SITE_NAME',
  SITE_DESCRIPTION: 'SITE_DESCRIPTION',
  SITE_LOGO_MEDIA_ID: 'SITE_LOGO_MEDIA_ID',
  SITE_LOGO_ALT: 'SITE_LOGO_ALT',
  SITE_FAVICON_MEDIA_ID: 'SITE_FAVICON_MEDIA_ID',
  SITE_OG_IMAGE_MEDIA_ID: 'SITE_OG_IMAGE_MEDIA_ID',
  SITE_DOMAIN: 'SITE_DOMAIN',
  SITE_DOMAIN_VERIFIED: 'SITE_DOMAIN_VERIFIED',
  CONCURRENT_LOGIN_ENABLED: 'CONCURRENT_LOGIN_ENABLED',
  UPLOAD_ALLOWED_EXTENSIONS: 'UPLOAD_ALLOWED_EXTENSIONS',
  UPLOAD_ALLOWED_MIME_TYPES: 'UPLOAD_ALLOWED_MIME_TYPES',
  UPLOAD_MAX_FILE_SIZE_MB: 'UPLOAD_MAX_FILE_SIZE_MB',
  ROBOTS_ADDITIONAL_DISALLOW: 'ROBOTS_ADDITIONAL_DISALLOW',
  SITE_FOOTER_CONFIG: 'SITE_FOOTER_CONFIG',
  FEEDBACK_IP_SALT: 'FEEDBACK_IP_SALT',
} as const;

export type SiteSettingKey =
  (typeof SITE_SETTING_KEYS)[keyof typeof SITE_SETTING_KEYS];
